void bottomline (void);
void bottomhp (void);
void bottomspell (void);
void bottomline (void);
void bottomgold (void);
void draws (int, int, int, int);
void drawscreen (void);
void showcell (int, int);
void show1cell (int, int);
void showplayer (void);
int moveplayer (int);
void seemagic (int);
void readcolors(void);
void compareequipped(int);
void statusmessage_draw_lines(void);
void statusmessage_draw_right_panel(void);
