void inventoryline_print(int);
void init_inventory (void);
int showstr (void);
int showwear (void);
int showwield (void);
int showread (void);
int showeat (void);
int showquaff (void);
int take (int, int);
int drop_object (int);
int pocketfull (void);
