SRC = $(wildcard *.c)
OBJ = $(SRC:.c=.o)
DEP = $(OBJ:.o=.d)
CC = gcc
CFLAGS = -Wall -Werror -std=gnu17 -pedantic -DWINDOWS -DMULTIPLE_SCORE_ENTRY -DEXTRA
LDFLAGS = -lm -lpdcurses

larn: $(OBJ)
	$(CC) -o $@ $^ $(LDFLAGS)

-include $(DEP)

%.d: %.c
	@$(CPP) $(CFLAGS) $< -MM -MT $(@:.d=.o) >$@

.PHONY: clean
clean:
	del $(OBJ)
	del $(DEP)