SRC = $(wildcard *.c)
OBJ = $(SRC:.c=.o)
DEP = $(OBJ:.o=.d)
CFLAGS = -Wall -Werror -std=c99 -pedantic -DWINDOWS -DMULTIPLE_SCORE_ENTRY -DEXTRA
LDFLAGS = -lm -lncurses

larn: $(OBJ)
	$(CC) -o $@ $^ $(LDFLAGS)

-include $(DEP)

%.d: %.c
	@$(CPP) $(CFLAGS) $< -MM -MT $(@:.d=.o) >$@

.PHONY: clean
clean:
	rm -f $(OBJ) mygame

.PHONY: cleandep
cleandep:
	rm -f $(DEP)

.PHONY: prep
prep:
	mkdir ~/.larn
	cp ./larnmazefile ~/.larn
	cp ./larnforts ~/.larn
