SRC = $(wildcard *.c)
OBJ = $(SRC:.c=.o)
DEP = $(OBJ:.o=.d)
CC = gcc
CFLAGS = -Wall -Werror -std=c99 -pedantic -DWINDOWS -DMULTIPLE_SCORE_ENTRY -DEXTRA
LDFLAGS = -lm -lncurses

larn: $(OBJ)
	$(CC) -o $@ $^ $(LDFLAGS)

-include $(DEP)

%.d: %.c
	@$(CPP) $(CFLAGS) $< -MM -MT $(@:.d=.o) >$@

.PHONY: clean
clean:
	del $(OBJ) mygame

.PHONY: cleandep
cleandep:
	del $(DEP)

.PHONY: prep
prep:
	mkdir "%USERPROFILE%/.larn"
	copy larnmazefile "%USERPROFILE%/.larn"
	copy larnforts "%USERPROFILE%/.larn"
